changelog = true
staticDirectories = ['static']

[docusaurus]
onBrokenLinks = "warn"
# url = "https://github.com/michaeldougal/AnimNation"
baseUrl = "/AnimNation/"
favicon = "/img/favicon.ico"

[colorMode]
defaultMode = "dark"
disableSwitch = true
respectPrefersColorScheme = false

[home]
enabled = false
includeReadme = true # Optional

[footer]
style = "dark"
copyright = "Copyright Â© 2025 Michael Dougal. Built with Moonwave and Docusaurus"

[navbar]
title = ""

[navbar.logo]
alt = 'Logo'
src = '/img/logo.png'
href = '/'
target = '_self'
